spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "{cipher}22eac15cffd2b9458bcce7dcd211f804ae748b2d26ad1212ef0017a7d9a1d425"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true

info:
  app:
    name: User Service
    description: This service handles user CRUD operations
    version: 1.0.0
    author: Ahmed Salah